// @ts-check
/**
 * Property 18: Wire-format round-trip and robustness.
 *
 * Validates: Requirements 12.3, 12.4, 12.5
 *
 * `toWirePayload(toLocalRow(m).value).value ≡ m` over the 14 fields listed in
 * Req 12.3 — for `m` generated by `arbServerMessage` covering:
 *   - all message types: `text`, `file`, `call`
 *   - DM and channel variants
 *   - optional `replyTo` (null and populated)
 *   - arbitrary `fileMetadata` (unicode keys/values, nested objects)
 *   - both `sender` / `receiver` shapes (bare id string and `{ _id }` subdoc)
 *   - injected unknown fields at the top level (must be ignored, not throw)
 *
 * Equivalence is structural over the 14 fields; the round-trip is allowed to
 * canonicalize representations (`sender: "abc"` ≡ `sender: { _id: "abc" }`,
 * missing `fileMetadata` ≡ `{}`, missing `replyTo` ≡ `null`, etc.).
 */

import { describe, it, expect } from "vitest";
import fc from "fast-check";

import { toLocalRow, toWirePayload } from "./wireFormat.js";

// ---------------------------------------------------------------------------
// Canonicalizer for the 14 round-trip fields
// ---------------------------------------------------------------------------

const ROUND_TRIP_FIELDS = [
  "_id",
  "sender",
  "receiver",
  "messageType",
  "content",
  "fileUrl",
  "fileName",
  "fileMetadata",
  "replyTo",
  "status",
  "channelId",
  "deletedForEveryone",
  "createdAt",
  "updatedAt",
];

const normSender = (s) =>
  typeof s === "string" ? { _id: s } : { _id: s._id };

const normReceiver = (r) => {
  if (r == null) return null;
  return typeof r === "string" ? { _id: r } : { _id: r._id };
};

/**
 * Project a wire-format-shaped object onto the 14 round-trip fields, applying
 * the canonicalization the serializer is allowed to perform: subdoc form for
 * sender/receiver, `{}` for absent `fileMetadata`, `null` for absent `replyTo`,
 * `null` for absent string-shaped optionals, and `false` for absent booleans.
 */
const project = (obj) => ({
  _id: obj._id,
  sender: normSender(obj.sender),
  receiver: normReceiver(obj.receiver),
  messageType: obj.messageType,
  content: typeof obj.content === "string" ? obj.content : null,
  fileUrl: typeof obj.fileUrl === "string" ? obj.fileUrl : null,
  fileName: typeof obj.fileName === "string" ? obj.fileName : null,
  fileMetadata:
    obj.fileMetadata == null
      ? {}
      : /** @type {Record<string, unknown>} */ (obj.fileMetadata),
  replyTo: obj.replyTo == null ? null : obj.replyTo,
  status: obj.status,
  channelId: typeof obj.channelId === "string" ? obj.channelId : null,
  deletedForEveryone: obj.deletedForEveryone === true,
  createdAt: obj.createdAt,
  updatedAt: obj.updatedAt,
});

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

const arbId = () =>
  fc
    .uuid()
    .map((u) => u.replace(/-/g, "")); // dense alphanumeric, easy to inspect

const arbIsoDate = () =>
  fc
    .date({ min: new Date("2000-01-01T00:00:00Z"), max: new Date("2099-12-31T23:59:59Z") })
    .map((d) => d.toISOString());

const arbStatus = () =>
  fc.constantFrom("sent", "delivered", "read");

/**
 * `sender` / `receiver` may arrive as a bare id string OR a populated subdoc
 * with extra fields (the backend sometimes `.populate()`s these). Either form
 * must round-trip correctly.
 */
const arbUserRef = () =>
  fc.oneof(
    arbId(),
    fc.record({
      _id: arbId(),
      // Extra populated fields the serializer must ignore:
      firstName: fc.option(fc.string({ maxLength: 16 }), { nil: undefined }),
      lastName: fc.option(fc.string({ maxLength: 16 }), { nil: undefined }),
      email: fc.option(
        fc.string({ minLength: 1, maxLength: 16 }).map((s) => `${s}@x.io`),
        { nil: undefined }
      ),
    })
  );

/**
 * Arbitrary JSON-compatible plain-object value. Constrained to keep the
 * generation tractable; size cap 4 levels deep, max 6 keys per object.
 *
 * Includes unicode keys/values and nested objects to cover the
 * "arbitrary fileMetadata" requirement of Property 18.
 */
const arbJsonObject = () => {
  const arbScalar = fc.oneof(
    fc.string({ maxLength: 32 }), // includes unicode-capable strings
    fc.integer({ min: -1_000_000, max: 1_000_000 }),
    fc.double({
      noNaN: true,
      noDefaultInfinity: true,
      min: -1e6,
      max: 1e6,
    }).map((v) => (Object.is(v, -0) ? 0 : v)),
    fc.boolean(),
    fc.constant(null)
  );

  const { jsonObject } = fc.letrec((tie) => ({
    jsonValue: fc.oneof(
      { maxDepth: 3 },
      arbScalar,
      fc.array(tie("jsonValue"), { maxLength: 4 }),
      tie("jsonObject")
    ),
    jsonObject: fc.dictionary(
      fc.string({ minLength: 1, maxLength: 12 }),
      tie("jsonValue"),
      { maxKeys: 6 }
    ),
  }));

  return jsonObject;
};

/**
 * `replyTo` subdoc as the backend ships it. Either `null` or a structured
 * preview reference.
 */
const arbReplyTo = () =>
  fc.option(
    fc.record(
      {
        messageId: arbId(),
        senderId: arbId(),
        messageType: fc.constantFrom("text", "file", "call"),
        previewText: fc.option(fc.string({ maxLength: 64 }), {
          nil: undefined,
        }),
        fileName: fc.option(
          fc
            .string({ minLength: 1, maxLength: 32 })
            .map((s) => `${s}.bin`),
          { nil: undefined }
        ),
        createdAt: fc.option(arbIsoDate(), { nil: undefined }),
      },
      { requiredKeys: ["messageId", "senderId", "messageType"] }
    ),
    { nil: null }
  );

/**
 * Inject N unknown top-level keys into `obj`. Keys are guaranteed not to
 * collide with reserved field names by prefixing them with `__unknown__`.
 */
const withUnknownFields = (obj, unknownEntries) => {
  const out = { ...obj };
  for (const [k, v] of unknownEntries) {
    out[`__unknown__${k}`] = v;
  }
  return out;
};

const arbUnknownEntries = () =>
  fc.array(
    fc.tuple(
      fc.string({ minLength: 1, maxLength: 8 }),
      fc.oneof(
        fc.string({ maxLength: 16 }),
        fc.integer(),
        fc.boolean(),
        fc.constant(null)
      )
    ),
    { maxLength: 4 }
  );

/**
 * Server message arbitrary: a single, valid `ServerMessage` payload that the
 * backend could ship.
 */
const arbServerMessage = () =>
  fc
    .record({
      _id: arbId(),
      sender: arbUserRef(),
      // `conversationVariant` chooses DM vs channel; receiver / channelId are
      // adjusted accordingly downstream.
      conversationVariant: fc.constantFrom("dm", "channel"),
      receiverRef: arbUserRef(),
      channelIdValue: arbId(),
      messageType: fc.constantFrom("text", "file", "call"),
      // Per-type required fields are filled in below.
      textContent: fc.string({ maxLength: 200 }),
      fileUrl: fc
        .string({ minLength: 1, maxLength: 64 })
        .map((s) => `https://cdn.example.com/${s}`),
      fileName: fc
        .string({ minLength: 1, maxLength: 32 })
        .map((s) => `${s}.bin`),
      callContent: fc.option(fc.string({ maxLength: 64 }), { nil: undefined }),
      fileMetadata: fc.option(arbJsonObject(), { nil: undefined }),
      replyTo: arbReplyTo(),
      status: arbStatus(),
      deletedForEveryone: fc.boolean(),
      createdAt: arbIsoDate(),
      updatedAt: arbIsoDate(),
      unknown: arbUnknownEntries(),
    })
    .map((seed) => {
      /** @type {Record<string, unknown>} */
      const m = {
        _id: seed._id,
        sender: seed.sender,
        messageType: seed.messageType,
        status: seed.status,
        deletedForEveryone: seed.deletedForEveryone,
        createdAt: seed.createdAt,
        updatedAt: seed.updatedAt,
      };

      if (seed.conversationVariant === "dm") {
        m.receiver = seed.receiverRef;
        // channelId omitted on purpose
      } else {
        m.channelId = seed.channelIdValue;
        // receiver omitted on purpose
      }

      if (seed.messageType === "text") {
        m.content = seed.textContent;
      } else if (seed.messageType === "file") {
        m.fileUrl = seed.fileUrl;
        m.fileName = seed.fileName;
      } else {
        // call
        if (seed.callContent !== undefined) m.content = seed.callContent;
      }

      if (seed.fileMetadata !== undefined) m.fileMetadata = seed.fileMetadata;
      if (seed.replyTo !== null) m.replyTo = seed.replyTo;

      return withUnknownFields(m, seed.unknown);
    });

// ---------------------------------------------------------------------------
// Property
// ---------------------------------------------------------------------------

describe("wireFormat round-trip (Property 18)", () => {
  it("toWirePayload(toLocalRow(m)) ≡ m over the 14 round-trip fields", () => {
    fc.assert(
      fc.property(arbServerMessage(), (m) => {
        const local = toLocalRow(m);
        if (!local.ok) {
          // The arbitrary only generates well-formed payloads; any failure
          // here is a test bug or a serializer regression.
          throw new Error(
            `toLocalRow rejected a valid payload: ${JSON.stringify(/** @type {any} */ (local).error)}`
          );
        }

        const wire = toWirePayload(local.value);
        if (!wire.ok) {
          throw new Error(
            `toWirePayload rejected a valid row: ${JSON.stringify(/** @type {any} */ (wire).error)}`
          );
        }

        expect(project(wire.value)).toEqual(project(m));
      }),
      { numRuns: 500 }
    );
  });

  it("ignores unknown top-level fields (Req 12.4) — output has no leaked keys", () => {
    fc.assert(
      fc.property(arbServerMessage(), (m) => {
        const local = toLocalRow(m);
        expect(local.ok).toBe(true);
        if (!local.ok) return;

        const wire = toWirePayload(local.value);
        expect(wire.ok).toBe(true);
        if (!wire.ok) return;

        // No `__unknown__*` key survives into the local row or the wire payload.
        for (const key of Object.keys(local.value)) {
          expect(key.startsWith("__unknown__")).toBe(false);
        }
        for (const key of Object.keys(wire.value)) {
          expect(key.startsWith("__unknown__")).toBe(false);
        }
      }),
      { numRuns: 200 }
    );
  });

  it("project() covers exactly the 14 fields named in Req 12.3", () => {
    // Sentinel test: if someone changes ROUND_TRIP_FIELDS or project(), the
    // property above might silently lose coverage of a required field.
    expect(ROUND_TRIP_FIELDS.length).toBe(14);
    const projected = project({
      _id: "x",
      sender: "a",
      receiver: null,
      messageType: "text",
      content: "",
      fileUrl: null,
      fileName: null,
      fileMetadata: {},
      replyTo: null,
      status: "sent",
      channelId: null,
      deletedForEveryone: false,
      createdAt: "2020-01-01T00:00:00Z",
      updatedAt: "2020-01-01T00:00:00Z",
    });
    expect(Object.keys(projected).sort()).toEqual([...ROUND_TRIP_FIELDS].sort());
  });
});
